<?php
namespace Fabiang;
use \org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-20 at 18:31:42.
 */
class DependencyComposerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DependencyComposer
     */
    protected $object;

    /**
     * @var  vfsStreamDirectory
     */
    protected $root;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->root = vfsStream::setup('composerPath');
        $composerLock = vfsStream::url('composerPath') . '/composer.lock';
        file_put_contents($composerLock, '{}');
        $this->object = new DependencyComposer($composerLock);
    }

    /**
     * Test setting and getting path to composer.lock.
     *
     * @covers \Fabiang\DependencyComposer::setComposerLock
     * @covers \Fabiang\DependencyComposer::getComposerLock
     *
     * @return void
     */
    public function testSetAndGetComposerLock()
    {
        $composerLock = vfsStream::url('composerPath') . '/composer.lock';
        file_put_contents($composerLock, '{}');

        $this->assertSame(
            $composerLock,
            $this->object->setComposerLock($composerLock)->getComposerLock()
        );
    }

    /**
     * Test setting and getting path to composer.lock.
     *
     * @covers \Fabiang\DependencyComposer::setComposerLock
     * @covers \Fabiang\DependencyComposer::getComposerLock
     *
     * @return void
     */
    public function testSetComposerLockWithDir()
    {
        $composerLock = vfsStream::url('composerPath') . '/composer.lock';
        file_put_contents($composerLock, '{}');

        $this->assertSame(
            $composerLock,
            $this->object->setComposerLock(dirname($composerLock))
                ->getComposerLock()
        );
    }

    /**
     * Test setting and getting path to composer.lock.
     *
     * @covers \Fabiang\DependencyComposer::setComposerLock
     * @expectedException Fabiang\DependencyComposer\Exception\InvalidArgumentException
     * @expectedExceptionMessage "composer.lock" could not be found in given path "vfs://composerPath"
     *
     * @return void
     */
    public function testSetComposerLockNotExisting()
    {
        unlink(vfsStream::url('composerPath') . '/composer.lock');
        $this->assertFalse($this->root->hasChild('composer.lock'));
        $composerLock = vfsStream::url('composerPath') . '/composer.lock';
        $this->object->setComposerLock($composerLock);
    }
}
